/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* src = "uart_rx.sv:2.1-107.10" *)
module uart_rx(clk, rst, rx, rx_data, rx_done);
  (* src = "uart_rx.sv:27.1-105.4" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _195_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _196_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _197_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _198_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _199_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _200_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _201_;
  (* src = "uart_rx.sv:0.0-0.0" *)
  wire _202_;
  (* force_downto = 32'd1 *)
  (* src = "uart_rx.sv:75.34-75.47|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _203_;
  (* force_downto = 32'd1 *)
  (* src = "uart_rx.sv:75.34-75.47|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _204_;
  (* force_downto = 32'd1 *)
  (* src = "uart_rx.sv:0.0-0.0|uart_rx.sv:37.9-101.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [7:0] _205_;
  (* src = "uart_rx.sv:24.13-24.22" *)
  reg [2:0] bit_index;
  (* src = "uart_rx.sv:5.17-5.20" *)
  input clk;
  wire clk;
  (* src = "uart_rx.sv:25.32-25.41" *)
  reg [7:0] clk_count;
  (* src = "uart_rx.sv:23.13-23.21" *)
  reg [7:0] data_reg;
  (* src = "uart_rx.sv:6.17-6.20" *)
  input rst;
  wire rst;
  (* src = "uart_rx.sv:7.17-7.19" *)
  input rx;
  wire rx;
  (* src = "uart_rx.sv:9.24-9.31" *)
  output [7:0] rx_data;
  reg [7:0] rx_data;
  (* src = "uart_rx.sv:10.18-10.25" *)
  output rx_done;
  wire rx_done;
  (* onehot = 32'd1 *)
  reg [4:0] state;
  assign _154_ = ~rst;
  assign _155_ = ~state[3];
  assign _156_ = state[4] | state[2];
  assign _157_ = _156_ | state[0];
  assign _158_ = _155_ & ~(_157_);
  assign _006_ = _154_ & ~(_158_);
  assign _159_ = clk_count[7] | clk_count[6];
  assign _160_ = clk_count[6] & ~(clk_count[7]);
  assign _161_ = clk_count[5] | clk_count[4];
  assign _162_ = _160_ & ~(_161_);
  assign _163_ = _159_ & ~(_162_);
  assign _164_ = clk_count[5] | ~(clk_count[4]);
  assign _165_ = _160_ & ~(_164_);
  assign _166_ = clk_count[3] | clk_count[2];
  assign _167_ = clk_count[3] | ~(clk_count[2]);
  assign _168_ = ~(clk_count[1] & clk_count[0]);
  assign _169_ = _168_ & ~(_167_);
  assign _170_ = _166_ & ~(_169_);
  assign _171_ = _165_ & ~(_170_);
  assign _172_ = _163_ & ~(_171_);
  assign _173_ = clk_count[0] | ~(clk_count[1]);
  assign _174_ = _173_ | _167_;
  assign _175_ = _165_ & ~(_174_);
  assign _176_ = _175_ | _172_;
  assign _177_ = state[4] & ~(_176_);
  assign _124_ = ~(bit_index[1] & bit_index[0]);
  assign _178_ = bit_index[2] & ~(_124_);
  assign _179_ = ~(_178_ & _176_);
  assign _180_ = state[2] & ~(_179_);
  assign _004_ = _180_ | _177_;
  assign _181_ = ~rx;
  assign _182_ = clk_count[1] & clk_count[0];
  assign _183_ = clk_count[2] | ~(clk_count[3]);
  assign _184_ = _182_ & ~(_183_);
  assign _185_ = clk_count[4] | ~(clk_count[5]);
  assign _186_ = _185_ | _159_;
  assign _187_ = _184_ & ~(_186_);
  assign _188_ = ~(_187_ & _181_);
  assign _189_ = state[3] & ~(_188_);
  assign _190_ = state[2] & ~(_176_);
  assign _191_ = _190_ | _189_;
  assign _192_ = _178_ | ~(_176_);
  assign _193_ = state[2] & ~(_192_);
  assign _002_ = _193_ | _191_;
  assign _194_ = state[0] & ~(rx);
  assign _009_ = state[3] & ~(_187_);
  assign _003_ = _009_ | _194_;
  assign _010_ = ~(_176_ & _154_);
  assign _005_ = state[4] & ~(_010_);
  assign _008_ = state[2] & ~(_010_);
  assign _011_ = ~(_187_ & rx);
  assign _012_ = state[3] & ~(_011_);
  assign _013_ = state[0] & rx;
  assign _014_ = _013_ | _012_;
  assign _001_ = _014_ | state[1];
  assign _015_ = state[2] ? _176_ : state[3];
  assign _016_ = _009_ | _180_;
  assign _017_ = _015_ & ~(_016_);
  assign _018_ = _012_ | rst;
  assign _007_ = _017_ & ~(_018_);
  assign _019_ = rx & clk_count[0];
  assign _020_ = _155_ & ~(_156_);
  assign _021_ = _176_ | clk_count[0];
  assign _022_ = _156_ & ~(_021_);
  assign _023_ = ~_019_;
  assign _024_ = _187_ ? _023_ : clk_count[0];
  assign _025_ = state[3] & ~(_024_);
  assign _026_ = _025_ | _022_;
  assign _205_[0] = _020_ ? _019_ : _026_;
  assign _027_ = clk_count[1] & rx;
  assign _028_ = ~(clk_count[1] ^ clk_count[0]);
  assign _029_ = _028_ | _176_;
  assign _030_ = _156_ & ~(_029_);
  assign _031_ = ~_027_;
  assign _032_ = _187_ ? _031_ : _028_;
  assign _033_ = state[3] & ~(_032_);
  assign _034_ = _033_ | _030_;
  assign _205_[1] = _020_ ? _027_ : _034_;
  assign _035_ = clk_count[2] & rx;
  assign _036_ = ~(_182_ ^ clk_count[2]);
  assign _037_ = _036_ | _176_;
  assign _038_ = _156_ & ~(_037_);
  assign _039_ = ~_035_;
  assign _040_ = _187_ ? _039_ : _036_;
  assign _041_ = state[3] & ~(_040_);
  assign _042_ = _041_ | _038_;
  assign _205_[2] = _020_ ? _035_ : _042_;
  assign _043_ = clk_count[3] & rx;
  assign _044_ = ~(_182_ & clk_count[2]);
  assign _045_ = _044_ ^ clk_count[3];
  assign _046_ = _045_ | _176_;
  assign _047_ = _156_ & ~(_046_);
  assign _048_ = ~_043_;
  assign _049_ = _187_ ? _048_ : _045_;
  assign _050_ = state[3] & ~(_049_);
  assign _051_ = _050_ | _047_;
  assign _205_[3] = _020_ ? _043_ : _051_;
  assign _052_ = clk_count[4] & rx;
  assign _053_ = ~(clk_count[3] & clk_count[2]);
  assign _054_ = _182_ & ~(_053_);
  assign _055_ = ~(_054_ ^ clk_count[4]);
  assign _056_ = _055_ | _176_;
  assign _057_ = _156_ & ~(_056_);
  assign _058_ = ~_052_;
  assign _059_ = _187_ ? _058_ : _055_;
  assign _060_ = state[3] & ~(_059_);
  assign _061_ = _060_ | _057_;
  assign _205_[4] = _020_ ? _052_ : _061_;
  assign _062_ = clk_count[5] & rx;
  assign _063_ = ~(_054_ & clk_count[4]);
  assign _064_ = _063_ ^ clk_count[5];
  assign _065_ = _064_ | _176_;
  assign _066_ = _156_ & ~(_065_);
  assign _067_ = ~_062_;
  assign _068_ = _187_ ? _067_ : _064_;
  assign _069_ = state[3] & ~(_068_);
  assign _070_ = _069_ | _066_;
  assign _205_[5] = _020_ ? _062_ : _070_;
  assign _071_ = clk_count[6] & rx;
  assign _072_ = clk_count[5] & clk_count[4];
  assign _073_ = ~(_072_ & _054_);
  assign _074_ = _073_ ^ clk_count[6];
  assign _075_ = _074_ | _176_;
  assign _076_ = _156_ & ~(_075_);
  assign _077_ = ~_071_;
  assign _078_ = _187_ ? _077_ : _074_;
  assign _079_ = state[3] & ~(_078_);
  assign _080_ = _079_ | _076_;
  assign _205_[6] = _020_ ? _071_ : _080_;
  assign _081_ = clk_count[7] & rx;
  assign _082_ = _073_ | ~(clk_count[6]);
  assign _083_ = _082_ ^ clk_count[7];
  assign _084_ = _083_ | _176_;
  assign _085_ = _156_ & ~(_084_);
  assign _086_ = ~_081_;
  assign _087_ = _187_ ? _086_ : _083_;
  assign _088_ = state[3] & ~(_087_);
  assign _089_ = _088_ | _085_;
  assign _205_[7] = _020_ ? _081_ : _089_;
  assign _203_[0] = ~bit_index[0];
  assign _090_ = ~bit_index[2];
  assign _091_ = bit_index[1] | bit_index[0];
  assign _092_ = _090_ & ~(_091_);
  assign _093_ = ~(_092_ & _203_[0]);
  assign _094_ = ~(bit_index[1] ^ bit_index[0]);
  assign _204_[1] = ~_094_;
  assign _095_ = _204_[1] | _093_;
  assign _096_ = _091_ ^ _090_;
  assign _097_ = ~_096_;
  assign _098_ = _097_ | _095_;
  assign _099_ = _092_ & ~(_098_);
  assign _100_ = data_reg[0] & ~(_099_);
  assign _101_ = ~(_092_ & rx);
  assign _102_ = _101_ | bit_index[0];
  assign _103_ = _102_ | _204_[1];
  assign _104_ = _103_ | _097_;
  assign _105_ = _092_ & ~(_104_);
  assign _195_ = _105_ | _100_;
  assign _106_ = ~_092_;
  assign _107_ = bit_index[1] | ~(bit_index[0]);
  assign _108_ = _107_ | _096_;
  assign _109_ = _106_ & ~(_108_);
  assign _110_ = data_reg[1] & ~(_109_);
  assign _111_ = ~(bit_index[0] & rx);
  assign _112_ = _111_ | _094_;
  assign _113_ = _112_ | _096_;
  assign _114_ = _106_ & ~(_113_);
  assign _196_ = _114_ | _110_;
  assign _115_ = bit_index[0] | ~(bit_index[1]);
  assign _116_ = _115_ | _096_;
  assign _117_ = _106_ & ~(_116_);
  assign _118_ = data_reg[2] & ~(_117_);
  assign _119_ = _092_ | _181_;
  assign _120_ = _119_ | bit_index[0];
  assign _121_ = _120_ | _094_;
  assign _122_ = _121_ | _096_;
  assign _123_ = _106_ & ~(_122_);
  assign _197_ = _123_ | _118_;
  assign _125_ = _124_ | _096_;
  assign _126_ = _106_ & ~(_125_);
  assign _127_ = data_reg[3] & ~(_126_);
  assign _128_ = _111_ | ~(_094_);
  assign _129_ = _128_ | _096_;
  assign _130_ = _106_ & ~(_129_);
  assign _198_ = _130_ | _127_;
  assign _131_ = _092_ | bit_index[0];
  assign _132_ = _131_ | _204_[1];
  assign _133_ = _132_ | _096_;
  assign _134_ = _106_ & ~(_133_);
  assign _135_ = data_reg[4] & ~(_134_);
  assign _136_ = _120_ | _204_[1];
  assign _137_ = _136_ | _096_;
  assign _138_ = _106_ & ~(_137_);
  assign _199_ = _138_ | _135_;
  assign _139_ = _107_ | ~(_096_);
  assign _140_ = _106_ & ~(_139_);
  assign _141_ = data_reg[5] & ~(_140_);
  assign _142_ = _112_ | ~(_096_);
  assign _143_ = _106_ & ~(_142_);
  assign _200_ = _143_ | _141_;
  assign _144_ = _115_ | ~(_096_);
  assign _145_ = _106_ & ~(_144_);
  assign _146_ = data_reg[6] & ~(_145_);
  assign _147_ = _121_ | _097_;
  assign _148_ = _106_ & ~(_147_);
  assign _201_ = _148_ | _146_;
  assign _149_ = _124_ | ~(_096_);
  assign _150_ = _106_ & ~(_149_);
  assign _151_ = data_reg[7] & ~(_150_);
  assign _152_ = _128_ | ~(_096_);
  assign _153_ = _106_ & ~(_152_);
  assign _202_ = _153_ | _151_;
  assign _000_ = _176_ & state[4];
  assign _204_[2] = _124_ ^ _090_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[0] <= data_reg[0];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[1] <= data_reg[1];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[2] <= data_reg[2];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[3] <= data_reg[3];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[4] <= data_reg[4];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[5] <= data_reg[5];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[6] <= data_reg[6];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_005_) rx_data[7] <= data_reg[7];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_007_)
      if (!state[2]) bit_index[0] <= 1'h0;
      else bit_index[0] <= _203_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_007_)
      if (!state[2]) bit_index[1] <= 1'h0;
      else bit_index[1] <= _204_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_007_)
      if (!state[2]) bit_index[2] <= 1'h0;
      else bit_index[2] <= _204_[2];
  always @(posedge clk, posedge rst)
    if (rst) state[0] <= 1'h1;
    else state[0] <= _001_;
  always @(posedge clk, posedge rst)
    if (rst) state[1] <= 1'h0;
    else state[1] <= _000_;
  always @(posedge clk, posedge rst)
    if (rst) state[2] <= 1'h0;
    else state[2] <= _002_;
  always @(posedge clk, posedge rst)
    if (rst) state[3] <= 1'h0;
    else state[3] <= _003_;
  always @(posedge clk, posedge rst)
    if (rst) state[4] <= 1'h0;
    else state[4] <= _004_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[0] <= _195_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[1] <= _196_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[2] <= _197_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[3] <= _198_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[4] <= _199_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[5] <= _200_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[6] <= _201_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_008_) data_reg[7] <= _202_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[0] <= _205_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[1] <= _205_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[2] <= _205_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[3] <= _205_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[4] <= _205_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[5] <= _205_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[6] <= _205_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_rx.sv:27.1-105.4" *)
  always @(posedge clk)
    if (_006_) clk_count[7] <= _205_[7];
  assign _203_[2:1] = bit_index[2:1];
  assign _204_[0] = _203_[0];
  assign rx_done = state[1];
endmodule

(* dynports =  1  *)
(* src = "uart_tx.sv:2.1-105.10" *)
module uart_tx(clk, rst, tx_start, tx_data, tx, tx_busy, tx_done);
  (* src = "uart_tx.sv:29.1-103.4" *)
  wire [2:0] _000_;
  (* src = "uart_tx.sv:29.1-103.4" *)
  wire [7:0] _001_;
  (* src = "uart_tx.sv:29.1-103.4" *)
  wire _002_;
  (* src = "uart_tx.sv:29.1-103.4" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* force_downto = 32'd1 *)
  (* src = "uart_tx.sv:0.0-0.0|uart_tx.sv:42.9-101.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _086_;
  (* src = "uart_tx.sv:26.13-26.22" *)
  reg [2:0] bit_index;
  (* src = "uart_tx.sv:5.24-5.27" *)
  input clk;
  wire clk;
  (* src = "uart_tx.sv:27.32-27.41" *)
  reg [7:0] clk_count;
  (* src = "uart_tx.sv:25.13-25.21" *)
  reg [7:0] data_reg;
  (* src = "uart_tx.sv:6.24-6.27" *)
  input rst;
  wire rst;
  (* onehot = 32'd1 *)
  reg [4:0] state;
  (* src = "uart_tx.sv:10.24-10.26" *)
  output tx;
  reg tx;
  (* src = "uart_tx.sv:11.24-11.31" *)
  output tx_busy;
  reg tx_busy;
  (* src = "uart_tx.sv:8.24-8.31" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "uart_tx.sv:12.24-12.31" *)
  output tx_done;
  wire tx_done;
  (* src = "uart_tx.sv:7.24-7.32" *)
  input tx_start;
  wire tx_start;
  assign _046_ = state[0] & ~(tx_start);
  assign _004_ = _046_ | state[1];
  assign _047_ = state[2] | state[3];
  assign _048_ = state[0] | state[4];
  assign _009_ = _048_ | _047_;
  assign _049_ = ~state[4];
  assign _050_ = clk_count[7] | clk_count[6];
  assign _051_ = clk_count[6] & ~(clk_count[7]);
  assign _052_ = clk_count[5] | clk_count[4];
  assign _053_ = _051_ & ~(_052_);
  assign _054_ = _050_ & ~(_053_);
  assign _055_ = clk_count[5] | ~(clk_count[4]);
  assign _056_ = _051_ & ~(_055_);
  assign _057_ = clk_count[3] | clk_count[2];
  assign _058_ = clk_count[3] | ~(clk_count[2]);
  assign _059_ = ~(clk_count[1] & clk_count[0]);
  assign _060_ = _059_ & ~(_058_);
  assign _061_ = _057_ & ~(_060_);
  assign _062_ = _056_ & ~(_061_);
  assign _063_ = _054_ & ~(_062_);
  assign _064_ = clk_count[0] | ~(clk_count[1]);
  assign _065_ = _064_ | _058_;
  assign _066_ = _056_ & ~(_065_);
  assign _067_ = _066_ | _063_;
  assign _012_ = state[4] ? _067_ : state[0];
  assign _068_ = rst | ~(tx_start);
  assign _011_ = state[0] & ~(_068_);
  assign _069_ = state[4] & ~(_067_);
  assign _070_ = ~(bit_index[1] & bit_index[0]);
  assign _071_ = bit_index[2] & ~(_070_);
  assign _072_ = ~(_071_ & _067_);
  assign _073_ = state[2] & ~(_072_);
  assign _007_ = _073_ | _069_;
  assign _074_ = state[3] ? _067_ : state[2];
  assign _075_ = state[2] & ~(_067_);
  assign _076_ = _075_ | _073_;
  assign _010_ = _074_ & ~(_076_);
  assign _077_ = state[3] & ~(_067_);
  assign _078_ = tx_start & state[0];
  assign _006_ = _078_ | _077_;
  assign _079_ = _047_ | state[4];
  assign _008_ = _079_ | state[0];
  assign _080_ = _067_ ? state[3] : state[2];
  assign _081_ = _071_ | ~(_067_);
  assign _082_ = state[2] & ~(_081_);
  assign _005_ = _082_ | _080_;
  assign _083_ = _067_ | clk_count[0];
  assign _001_[0] = _079_ & ~(_083_);
  assign _084_ = ~(clk_count[1] ^ clk_count[0]);
  assign _085_ = _084_ | _067_;
  assign _001_[1] = _079_ & ~(_085_);
  assign _013_ = clk_count[1] & clk_count[0];
  assign _014_ = ~(_013_ ^ clk_count[2]);
  assign _015_ = _014_ | _067_;
  assign _001_[2] = _079_ & ~(_015_);
  assign _016_ = ~(_013_ & clk_count[2]);
  assign _017_ = _016_ ^ clk_count[3];
  assign _018_ = _017_ | _067_;
  assign _001_[3] = _079_ & ~(_018_);
  assign _019_ = ~(clk_count[3] & clk_count[2]);
  assign _020_ = _013_ & ~(_019_);
  assign _021_ = ~(_020_ ^ clk_count[4]);
  assign _022_ = _021_ | _067_;
  assign _001_[4] = _079_ & ~(_022_);
  assign _023_ = ~(_020_ & clk_count[4]);
  assign _024_ = _023_ ^ clk_count[5];
  assign _025_ = _024_ | _067_;
  assign _001_[5] = _079_ & ~(_025_);
  assign _026_ = clk_count[5] & clk_count[4];
  assign _027_ = ~(_026_ & _020_);
  assign _028_ = _027_ ^ clk_count[6];
  assign _029_ = _028_ | _067_;
  assign _001_[6] = _079_ & ~(_029_);
  assign _030_ = _027_ | ~(clk_count[6]);
  assign _031_ = _030_ ^ clk_count[7];
  assign _032_ = _031_ | _067_;
  assign _001_[7] = _079_ & ~(_032_);
  assign _000_[0] = state[2] & ~(bit_index[0]);
  assign _033_ = ~(bit_index[1] ^ bit_index[0]);
  assign _000_[1] = state[2] & ~(_033_);
  assign _034_ = _070_ ^ bit_index[2];
  assign _000_[2] = state[2] & ~(_034_);
  assign _002_ = tx_start & ~(state[4]);
  assign _035_ = ~state[2];
  assign _036_ = bit_index[0] ? data_reg[1] : data_reg[0];
  assign _037_ = bit_index[0] ? data_reg[3] : data_reg[2];
  assign _038_ = bit_index[1] ? _037_ : _036_;
  assign _039_ = bit_index[0] ? data_reg[5] : data_reg[4];
  assign _040_ = bit_index[0] ? data_reg[7] : data_reg[6];
  assign _041_ = bit_index[1] ? _040_ : _039_;
  assign _042_ = bit_index[2] ? _041_ : _038_;
  assign _043_ = _042_ & ~(_035_);
  assign _044_ = _043_ | _048_;
  assign _045_ = _035_ & ~(_048_);
  assign _086_ = _044_ & ~(_045_);
  assign _003_ = _067_ & ~(_049_);
  always @(posedge clk, posedge rst)
    if (rst) state[0] <= 1'h1;
    else state[0] <= _004_;
  always @(posedge clk, posedge rst)
    if (rst) state[1] <= 1'h0;
    else state[1] <= _003_;
  always @(posedge clk, posedge rst)
    if (rst) state[2] <= 1'h0;
    else state[2] <= _005_;
  always @(posedge clk, posedge rst)
    if (rst) state[3] <= 1'h0;
    else state[3] <= _006_;
  always @(posedge clk, posedge rst)
    if (rst) state[4] <= 1'h0;
    else state[4] <= _007_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[0] <= 1'h0;
    else if (_008_) clk_count[0] <= _001_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[1] <= 1'h0;
    else if (_008_) clk_count[1] <= _001_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[2] <= 1'h0;
    else if (_008_) clk_count[2] <= _001_[2];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[3] <= 1'h0;
    else if (_008_) clk_count[3] <= _001_[3];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[4] <= 1'h0;
    else if (_008_) clk_count[4] <= _001_[4];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[5] <= 1'h0;
    else if (_008_) clk_count[5] <= _001_[5];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[6] <= 1'h0;
    else if (_008_) clk_count[6] <= _001_[6];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_count[7] <= 1'h0;
    else if (_008_) clk_count[7] <= _001_[7];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx <= 1'h1;
    else if (_009_) tx <= _086_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) tx_busy <= 1'h0;
    else if (_012_) tx_busy <= _002_;
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[0] <= tx_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[1] <= tx_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[2] <= tx_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[3] <= tx_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[4] <= tx_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[5] <= tx_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[6] <= tx_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk)
    if (_011_) data_reg[7] <= tx_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_index[0] <= 1'h0;
    else if (_010_) bit_index[0] <= _000_[0];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_index[1] <= 1'h0;
    else if (_010_) bit_index[1] <= _000_[1];
  (* \always_ff  = 32'd1 *)
  (* src = "uart_tx.sv:29.1-103.4" *)
  always @(posedge clk, posedge rst)
    if (rst) bit_index[2] <= 1'h0;
    else if (_010_) bit_index[2] <= _000_[2];
  assign tx_done = state[1];
endmodule
